# fly.toml app configuration file generated for hlirl-frontend on 2024-11-03T14:45:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hlirl-frontend'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
